name: zhao-oxide-bandgap

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - pymatgen
  - matminer
  - mp-api
  - python-dotenv